authors = ["mtsch <matijacufar@gmail.com>"]
name = "PersistenceDiagrams"
uuid = "d4d3c954-2605-11e9-0fc0-9b0a410a53f6"
version = "0.1.0"

[deps]

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
